Repository deshima-dev/simpleatm, pull requests merged in 2020-10, with the labels that each got.

#6 Release v0.1.0
  .github/workflows/pypi.yml
  .github/workflows/test.yml
  README.md
  pyproject.toml
  simpleatm/__init__.py
  tests/__init__.py
  tests/test_metadata.py
Labels: release

#9 Add models for tests
  poetry.lock
  pyproject.toml
  scripts/testmodels
  simpleatm/data/_test_fail.nc
  simpleatm/data/_test_pass.nc
Labels: feature

#11 Fix models for tests
  scripts/testmodels
  simpleatm/data/_test_fail.nc
  simpleatm/data/_test_pass.nc
Labels: bug

#12 Add data-loading feature
  simpleatm/__init__.py
  simpleatm/models.py
  tests/test_loaddata.py
Labels: feature
